export const dataArr = [
  {
    id: 'id1',
    name: 'Robert Brown',
    country: 'UK',
    phoneNumber: '+12345678900',
    signalPriority: 'MEDIUM',
    status: 'APPLIED',
    stars: 2,
    isNew: true,
    isFollowed: false,
    imgUrl: 'https://mui.com/static/images/avatar/1.jpg',
  },
  {
    id: 'id3',
    name: 'Alice Johnson',
    country: 'Australia',
    phoneNumber: '+12345678902',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 3,
    isNew: true,
    isFollowed: true,
    imgUrl: 'https://mui.com/static/images/avatar/1.jpg',
  },
  {
    id: 'id4',
    name: 'Sophia Young',
    country: 'Germany',
    phoneNumber: '+12345678903',
    signalPriority: 'MEDIUM',
    status: 'APPLIED',
    stars: 4,
    isNew: false,
    isFollowed: true,
    imgUrl: 'https://mui.com/static/images/avatar/2.jpg',
  },
  {
    id: 'id6',
    name: 'Liam Martinez',
    country: 'India',
    phoneNumber: '+12345678905',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 5,
    isNew: false,
    isFollowed: true,
    imgUrl: 'https://mui.com/static/images/avatar/1.jpg',
  },
  {
    id: 'id8',
    name: 'William Harris',
    country: 'Brazil',
    phoneNumber: '+12345678907',
    signalPriority: 'HIGH',
    status: 'INTERVIEW',
    stars: 1,
    isNew: false,
    isFollowed: false,
    imgUrl: 'https://mui.com/static/images/avatar/2.jpg',
  },
  {
    id: 'id9',
    name: 'James Lewis',
    country: 'South Africa',
    phoneNumber: '+12345678908',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 4,
    isNew: true,
    isFollowed: true,
    imgUrl: 'https://mui.com/static/images/avatar/3.jpg',
  },
  {
    id: 'id11',
    name: 'Olivia White',
    country: 'Canada',
    phoneNumber: '+12345678910',
    signalPriority: 'HIGH',
    status: 'INTERVIEW',
    stars: 3,
    isNew: true,
    isFollowed: false,
    imgUrl: 'https://mui.com/static/images/avatar/3.jpg',
  },
  {
    id: 'id12',
    name: 'Jane Smith',
    country: 'UK',
    phoneNumber: '+12345678911',
    signalPriority: 'LOW',
    status: 'SHORTLISTED',
    stars: 4,
    isNew: false,
    isFollowed: true,
    imgUrl: 'https://mui.com/static/images/avatar/2.jpg',
  },
];
